config/routes.rb
Rails.application.routes.draw do
 
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :stores,controllers: {
    registrations: 'stores/registrations',
    confirmations: 'stores/confirmations',
    sessions: 'stores/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :comments
  
  resources :storextras do
    resources :likes
  end
 
  resources :categories
  resources :storextras
  resources :products do
      resources :orders, only: :create do
    end
  end
  resources :users 
  resources :stores
  resources :orders, only: :index

  delete 'orders/clean', to: 'orders#clean', as: 'clean_orders'
  delete 'order/:id', to: 'orders#destroy', as: 'destroy_order'
  get 'orders/save', to: 'orders#save', as: 'save_orders'

  resources :billings, only: [] do
    collection do
      get 'pre-pay'
      get 'execute'
    end 
  end 
  
  post 'storextras/:id', to: 'comments#create', as:'comment_store'
  root to: 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :storextras, dependent: :destroy

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @categories = Category.where('name iLIKE ?', "%#{params[:q]}") if params[:q]
    @storextras = Storextra.order("rating ASC").page(params[:page])
    # @storextras = Storextra.where('description iLIKE ?', "%#{params[:q]}") if params[:q]
   
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
        <td><%= category.name %></td>
         <% if user_signed_in?%>
        <td><%= link_to 'Show', category %></td>
        <%end%>
         <% if admin_user_signed_in?%>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control col-md-4", :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if user_signed_in? %>
 <table class="table table-hover">
    <thead>
      <tr>
        <th>Categoría</th>
      </tr>
    </thead>
    <tbody id="table-category">
      <% @categories.each do |category| %>
        <tr >
          <td class="table-active"><%= category.name %></td>
          <% if user_signed_in?%>
          <td><%= link_to 'Show', category %></td>
          <%end%>
          <% if admin_user_signed_in?%>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
 </table>
<%end%>  
  <% if !user_signed_in? %>
    <% if  !store_signed_in? %>
      <div class="card text-white bg-success my-5 mx-5 px-5 text-center">
        <div class="card-header "></div>
        <div class="card-body">
          <h3 > Este es el lugar para encontrar la tienda que buscas o si tienes una tienda dejar que los clientes te encuentren</h3>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col text-center mt-5">
              <%= button_to 'Crear una cuenta de usuario', new_user_registration_path, class: "btn btn-success ", method: :get %>  
          </div>
           <div class="col text-center my-5">
             <%= button_to 'Crear una cuenta para tiendas', new_store_registration_path, class: "btn btn-success ", method: :get %> 
           </div>
        </div>
      
       
      </div>
        
    <%end%>
  <%end%>
  <br>
  <h1 class="text-center my-5"> ¡Aquí encontrarás las mejores tiendas!</h1>
  <% @storextras.each do |storextra| %>
    <div class="card text-white bg-dark mb-3 ml-5 text-center" style="max-width: 90vw;">
      <div class="card-header "><h3> <%= storextra.store.name %></h3></div>
      <div class="card-body">
        <%=image_tag storextra.avatar, style: 'height:300px; width:300px;', class:"card-img-top" if storextra.avatar.attached?%>
      </div>
       <div class="card-footer">
        <%storextra.rating_prom(storextra)%> 
        <%= storextra.rating %> &#11088;
      </div>
      <% if user_signed_in?%>
        <div class="card-footer">
          <%= link_to 'Show', storextra %>
        </div>
      <%end%>
    </div>
  <%end%>
  <% if admin_user_signed_in? || user_signed_in? || store_signed_in?%>
  <h3 class="text-center"><%= link_to 'Entra aquí para buscar más Tiendas', storextras_path %></h3> <br>
  <%end%>
  <% if admin_user_signed_in?%>
    <%= link_to 'New Category', new_category_path %>
  <%end%>
</section>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <%= paginate @storextras %>
  </div>
</div>

app/views/categories/index.js.erb
$('#table-category').html("<%= j render @categories%>");

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<table class="table table-hover" >
  <thead>
    <tr>
      <th>Foto</th>
      <th>Nombre de la tienda</th>
      <th>Descripción</th>
    </tr>
  </thead>
  <tbody >
  <% @category.storextras.each do |storextra| %>
      <tr class="table-active">
        <td><%=image_tag storextra.avatar, style: 'height:150px; width:150px;' if storextra.avatar.attached? %></td> 
        <td><%= storextra.store.name %></td>
        <td><%= storextra.description %> </td>
        <% if user_signed_in?%>
          <td><%= link_to 'Show', storextra %></td>
        <%end%>
      </tr>    
  <%end%>
  </tbody>
</table>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>