config/routes.rb
Rails.application.routes.draw do
 
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :stores,controllers: {
    registrations: 'stores/registrations',
    confirmations: 'stores/confirmations',
    sessions: 'stores/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :comments
  
  resources :storextras do
    resources :likes
  end
 
  resources :categories
  resources :storextras
  resources :products do
      resources :orders, only: :create do
    end
  end
  resources :users 
  resources :stores
  resources :orders, only: :index

  delete 'orders/clean', to: 'orders#clean', as: 'clean_orders'
  delete 'order/:id', to: 'orders#destroy', as: 'destroy_order'
  get 'orders/save', to: 'orders#save', as: 'save_orders'

  resources :billings, only: [] do
    collection do
      get 'pre-pay'
      get 'execute'
    end 
  end 
  
  post 'storextras/:id', to: 'comments#create', as:'comment_store'
  root to: 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/storextra.rb
class Storextra < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_one_attached :avatar, dependent: :destroy 
  has_many :comments, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :avatar, content_type: [:png, :jpg, :jpeg]
  default_scope {order("rating DESC")}
  def rating_prom (storextra)
    @storextra = storextra
    comments = Comment.all
    rating_prom = 0
    contador = 0
    @storextra.comments.each do |comment|
      rating_prom += comment.rating.to_i
      contador += 1
    end 
    if rating_prom != 0
      @storextra.rating = rating_prom / contador
      @storextra.save!
    end 
  end
 
end

app/controllers/storextras_controller.rb
class StorextrasController < ApplicationController
  before_action :set_storextra, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_store!, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]
  # GET /storextras
  # GET /storextras.json
  def index
  
    @storextras = Storextra.order("rating ASC").page(params[:page]) unless  store_signed_in?
    @storextras = Storextra.where(store_id: current_store.id) if store_signed_in? 
    @q = Storextra.ransack(params[:q]) 
    @storextras = @q.result.includes(:store).page(params[:page])

    # @storextras = Storextra.where('description LIKE ?', "%#{params[:q]}%") if params[:q]
    #@products = Products.all.where(storextra_id: @storextra.id)
  
  end

  # GET /storextras/1
  # GET /storextras/1.json
  def show
    @storextra = Storextra.find(params[:id]) if store_signed_in? 
    @comment = Comment.new(rating: 0)
    @product = Product.new
    #@user = User.all
    #@comments = Comment.page(params[:page])
    #@comments = Comment.where(storextra_id: @storextra.id, user_id: @user).order("created_at ASC").page(params[:page])
  end

  # GET /storextras/new
  def new
    @store = Store.find_by(params[:id])
    @storextra = Storextra.new
  end

  # GET /storextras/1/edit
  def edit
  end

  # POST /storextras
  # POST /storextras.json
  def create
    @store = current_store
    @storextra = Storextra.new(storextra_params)
    @storextra.id = current_store.id
    @storextra.save!
    respond_to do |format|
      if @storextra.save
        format.html { redirect_to @storextra, notice: 'Storextra was successfully created.' }
        format.json { render :show, status: :created, location: @storextra }
      else
        format.html { render :new }
        format.json { render json: @storextra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storextras/1
  # PATCH/PUT /storextras/1.json
  def update
    respond_to do |format|
      if @storextra.update(storextra_params)
        format.html { redirect_to @storextra, notice: 'Storextra was successfully updated.' }
        format.json { render :show, status: :ok, location: @storextra }
      else
        format.html { render :edit }
        format.json { render json: @storextra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storextras/1
  # DELETE /storextras/1.json
  def destroy
    @storextra.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Has eliminado los datos de tu tienda!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storextra
      @storextra = Storextra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def storextra_params
      params.require(:storextra).permit(:description, :horario_open, :horario_close, :link_facebook, :link_instagram, :link_whatsapp, :link_web, :store_id, :category_id, :avatar , :rating)
    end
  protected
    def authenticate_user!
      redirect_to root_path, notice: "You must login" unless user_signed_in? || store_signed_in?
    end
end

app/helpers/storextras_helper.rb
module StorextrasHelper
end

app/views/storextras/_form.html.erb
<div class="form-group text-md-center">
  <%= form_with(model: storextra, local: true) do |form| %>
    <% if storextra.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(storextra.errors.count, "error") %> prohibited this storextra from being saved:</h2>

        <ul>
        <% storextra.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class:"form-control col-md-4", :required => true %>
    </div>

    <div class="field form-group">
      <%= form.label :horario_open %>
      <%= form.time_select :horario_open, class:"form-control col-md-4", :required => true %>
    </div>

    <div class="field form-group">
      <%= form.label :horario_close %>
      <%= form.time_select :horario_close, class:"form-control col-md-4", :required => true %>
    </div>

    <div class="field form-group">
      <%= form.label :link_facebook %>
      <%= form.text_field :link_facebook %>
    </div>

    <div class="field form-group">
      <%= form.label :link_instagram %>
      <%= form.text_field :link_instagram %>
    </div>

    <div class="field form-group">
      <%= form.label :link_whatsapp %>
      <%= form.text_field :link_whatsapp %>
    </div>

    <div class="field form-group">
      <%= form.label :link_web %>
      <%= form.text_field :link_web %>
    </div>
    <div class="field form-group">
      <%= form.hidden_field :store_id, value:current_store.id %>
    </div>

    <div class="field form-group">
      <%= form.label :category_id %> 
      <%= form.select :category_id, options_from_collection_for_select( Category.all, :id, :name), prompt: 'Elige una categoría', class:" col-md-4" %>
    </div>
    <div class="field form-group">
      <%= form.label :avatar, 'Sube la foto de tu tienda aquí' %> <br>
      <%= form.file_field :avatar, class:"form-control col-md-4" %> 
    </div>


    <div class="actions form-group">
      <button type="submit" class="btn btn-success">Enviar</button>
    </div>
  <% end %>
</div>

app/views/storextras/create.js.erb
//$('#table-storex').append('<%= j render @storextras%>');
//document.querySelector('#productos').innerHTML += ('<%= j render @post %>')

app/views/storextras/edit.html.erb
<h1>Editing Storextra</h1>

<%= render 'form', storextra: @storextra %>

<%= link_to 'Atrás', @storextra %> <br>

app/views/storextras/index.html.erb
<p id="notice"><%= notice %></p>
<h1> Busca aquí tu tienda: </h1> <br>
<% if user_signed_in? %>
 <div>
  <%= search_form_for @q do |f| %>
  <%= f.label 'Por nombre de la tienda: ' %>
  <%= f.search_field :store_name_cont %>
  <%= f.label 'Por su descripción:' %>
  <%= f.search_field :description_cont %>
    <%= f.submit%>
<% end %>
  </div>
<%end%>

 
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre de la tienda</th>
      <th>Calificación</th>
      <th>Descripción</th>
      <th>Horario de atención</th>
      <th>Link facebook</th>
      <th>Link instagram</th>
      <th>Link whatsapp</th>
      <th>Link web</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-active">
  <% @storextras.each do |storextra| %>
      <tr>
        <td><%= storextra.store.name %></td>
         <td><%= storextra.rating %></td>
        <%#=image_tag storextra.avatar, style: 'height:150px; width:150px;' if storextra.avatar.attached?%>
        <td><%= storextra.description %></td>
        <td><%= storextra.horario_open.strftime("%H:%M") %> a <%= storextra.horario_close.strftime("%H:%M") %></td>
        <td><%= storextra.link_facebook %></td>
        <td><%= storextra.link_instagram %></td>
        <td><%= storextra.link_whatsapp %></td>
        <td><%= storextra.link_web %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Show', storextra %></td>
        <%end%>
        <% if store_signed_in?%>
          <% if current_store.id == storextra.store_id%>
            <td><%= link_to 'Show', storextra %></td>
            <td><%= link_to 'Edit', edit_storextra_path(storextra) %></td>
          <%end%>
        <%end%>
    <%end%>
      </tr>    
  </tbody>
</table>
 
<br>

<%= link_to 'Inicio', root_path %>

 <div class="row">
  <div class="col-md-8 offset-md-2">
    <%= paginate @storextras %>
  </div>
</div>

app/views/storextras/index.js.erb
('#table-storex').html("<%= j render @storextras%>");

app/views/storextras/new.html.erb
<h1>New Storextra</h1>

<%= render 'form', storextra: @storextra %>

app/views/storextras/show.html.erb
<p id="notice"><%= notice %></p>
<% if store_signed_in? && @storextra.store_id == current_store.id%>
  <%= link_to 'Editar datos de la Tienda', edit_storextra_path(@storextra) %> <br>
   <%#= link_to ' Borrar', @storextra, method: :delete, data: { confirm: 'Estás seguro!!?' } %></p>
<%end%>

<div class="card text-white bg-dark mb-3 ml-5 text-center" style="max-width: 90vw;">
  <div class="card-header "><h3> <%= @storextra.store.name %></h3></div>
  <div class="card-body">
    <%=image_tag @storextra.avatar, style: 'height:300px; width:300px;', class:"card-img-top" if @storextra.avatar.attached?%>
    <h4 class="card-title">Descripción</h4>
    <p class="card-text"> <%= @storextra.description %></p>
    <h5 class="card-title">Dirección</h5>
    <p class="card-text"> <%= @storextra.store.address %></p>
    <h5 class="card-title">Teléfono</h5>
    <p class="card-text"> <%= @storextra.store.phone %></p>
    <h5 class="card-title">Calificación: </h5>
    <p class="card-text"> <%@storextra.rating_prom(@storextra)%> <%=@storextra.rating%> &#11088;</p>
    <h5 class="card-title">Horario de atención</h5>
    <p class="card-text"> <%= @storextra.horario_open.strftime("%H:%M") %> a <%= @storextra.horario_close.strftime("%H:%M") %></p>
    <h5 class="card-title">Link página web</h5>
    <p class="card-text"> <%=link_to "#{@storextra.link_web}", "https://#{@storextra.link_web}", :target => "_blank"%>
    <h5 class="card-title"><i class="fab fa-facebook-square text-white"></i></h5>
    <p class="card-text"> <%=link_to "#{@storextra.link_facebook}","https://#{@storextra.link_facebook}", :target => "_blank"%> </p>
    <h5 class="card-title"><i class="fab fa-instagram text-white"></i></h5>
    <p class="card-text"> <%=link_to "#{@storextra.link_instagram}", "https://#{@storextra.link_instagram}", :target => "_blank"%>
    <h5 class="card-title"><i class="fab fa-whatsapp-square text-white"></i></h5>
    <p class="card-text"> <%=link_to "#{@storextra.link_whatsapp}", "https://#{@storextra.link_whatsapp}", :target => "_blank"%>
  </div>
</div>


<% if user_signed_in?%>
  <h4 class="text-center"><% pre_like = @storextra.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= link_to raw('Quitar de favoritos &#x1F495; '), storextra_like_path(@storextra, pre_like), method: :delete %>  
  <% else %>
    <%= link_to raw('&#128128; Agregar a favoritos '), storextra_likes_path(@storextra), method: :post %> </h4>
  <% end %>
<%end%>
<p class="text-center"> <%= @storextra.likes.count %> <%= (@storextra.likes.count) == 1 ? ' Persona ha agregado esta tienda a sus favoritos' : ' Personas han agregado esta tienda a sus favoritos'%></p>
<br>
<% if store_signed_in? %>
  <% if current_store.id == @storextra.store_id%>
      <h3 class="text-center">Agrega un nuevo producto: </h3>
    <div class="form-group text-sm-center "> 
      <%= form_with(model: @product, data: {confirm: 'enviar datos?'}, id: 'form') do |form| %>
        <div class="field form-group ">
          <%= form.label :name, 'Nombre del producto: '%> <br>
          <%= form.text_field :name, class:"form-control  col-md-4 ", :required => true%>
        </div>

        <div class="field form-group">
          <%= form.label :description, 'Descripción: ' %> <br>
          <%= form.text_area :description, class:"form-control col-md-4", :required => true %>
        </div>

        <div class="field form-group">
          <%= form.label :stock, 'Stock: ' %>
          <%= form.number_field :stock, min: 1, class:"form-control col-md-4", :required => true %>
        </div>

        <div class="field form-group">
          <%= form.label :price, 'Precio: (Agrega el precio en dólares(USD))' %>
          <%= form.number_field :price, min: 0, class:"form-control col-md-4", :required => true %>
        </div>

        <div class="field form-group">
          <%= form.label :sku, 'SKU: ' %>
          <%= form.text_field :sku, class:"form-control col-md-4", :required => true %>
        </div>
        <div class="field form-group">
          <%= form.label :image, 'Agrega la foto del producto aquí' %> <br>
          <%= form.file_field :image, class:"form-control col-md-4", :required => true %> 
        </div>
        
        <div class="field form-group">
          <%= form.hidden_field :store_id, value: current_store.id %>
        </div>
        <div class="field form-group">
          <%= form.hidden_field :storextra_id, value: @storextra.id %>
        </div>
        <div class="actions form-group">
          <button type="submit" class="btn btn-success">Enviar</button>
        </div>
      <% end %>
    <%end%>
    </div>
<%end%>
<h2 class='text-center'>Productos</h2>
<div class="card-deck">
    <% @storextra.products.each do |product|  %>
    <div class='card text-white bg-warning mb-3'>
        <%= image_tag product.image, class: 'card-img-top img-fluid'%>
            <h5 class='card-title'><%= product.name %></h5>
        <div class='card-body'>
                <div class='card-text'>
                    <div>
                        Precio: US $<%= product.price %> |
                        Stock: <%= product.stock %> |
                         Producto agregado el: <%= product.created_at.to_formatted_s(:long) %>
                        <% if !store_signed_in?%>
                          
                          <%= button_to "Agregar al carro", product_orders_path(product.id), class: "btn btn-success", method: :post %>
                           
                        <%elsif store_signed_in?%>
                          <%= button_to 'Editar producto', edit_product_path(product), class: "btn btn-success", method: :get %> <br>
                          <%= button_to 'Eliminar Producto', product, class: "btn btn-success", method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%end%>
                    </div>
                    
                </div>
        </div>
    </div>    
    <%end%>
</div>
<br>


<br>
<h3 class="text-center">Comentarios</h3>
<% if user_signed_in?%>
<div class="form-group text-md-center">
  <%= form_with(model: @comment, local: true) do |form| %>

    <div class="field form-group text-md-center">
      <%= form.label :content, "Deja tu comentario aquí!" %> <br>
      <%= form.text_area :content, class:"form-control col-md-4", :required => true %>
    </div>
    <div class="field form-group text-md-center">
      <%= form.label :rating,  "Deja tu calificación aquí (0-5)" %> <br>
      <%= form.number_field :rating, min: 0, max: 5 %>
    </div>

    <div class="field form-group text-md-center">
      <%= form.hidden_field :user_id, value:current_user.id %>
    </div>
    <div class="field">
      <%= form.hidden_field :storextra_id, value: @storextra.id %>
    </div>
    <div class="actions form-group text-md-center">
      <button type="submit" class="btn btn-success">Enviar</button>
    </div>
  <% end %>
  </div>
<%end%>
<% @storextra.comments.each do |comment|%>
<div class="card text-white bg-success mb-3 ml-5 text-center" style="max-width: 90vw;">
  <div class="card-header"><%= comment.user.name %></div>
  <div class="card-body">
    <h5 class="card-title"><% comment.rating.to_i.times do  %>
    	&#11088;
  <% end %>
  <% comment.blank_stars.times do  %>
  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-star" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
  </svg>
  <% end %></h5>
    <p class="card-text"><%= comment.content %></p>
    <p class="card-footer"><%= time_ago_in_words(comment.created_at) %></p>
    <p class="card-footer"><%= link_to "#{comment.user.name}", user_path(comment.user.id) %></p>
    <p class="card-footer"><% if user_signed_in? && comment.user_id == current_user.id%>
      <%= link_to ' Editar', edit_comment_path(comment) %>
      <%= link_to ' Borrar Comentario', comment, method: :delete, data: { confirm: 'Estás seguro?' } %></p>  
    <%end%>
  </div>
</div>
  <%end%>


 <%= link_to 'Inicio', root_path %>

<%# <div class="row">
  <div class="col-md-8 offset-md-2">
    <%#= paginate @comments %>
  <%#</div>
<%#/div> %>