config/routes.rb
Rails.application.routes.draw do
 
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :stores,controllers: {
    registrations: 'stores/registrations',
    confirmations: 'stores/confirmations',
    sessions: 'stores/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :comments
  
  resources :storextras do
    resources :likes
  end
 
  resources :categories
  resources :storextras
  resources :products do
      resources :orders, only: :create do
    end
  end
  resources :users 
  resources :stores
  resources :orders, only: :index

  delete 'orders/clean', to: 'orders#clean', as: 'clean_orders'
  delete 'order/:id', to: 'orders#destroy', as: 'destroy_order'
  get 'orders/save', to: 'orders#save', as: 'save_orders'

  resources :billings, only: [] do
    collection do
      get 'pre-pay'
      get 'execute'
    end 
  end 
  
  post 'storextras/:id', to: 'comments#create', as:'comment_store'
  root to: 'categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
    belongs_to :user
    has_many :orders, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :storextras, dependent: :destroy

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :storextra

  # default_scope {where(storextra_id: @storextra).order("created_at DESC").limit(15)}
  validates :rating,  numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 0, only_integer: true }
  validates :content, length: {maximum: 1000, message: 'El máximo es de 1000 caracteres!'}

  def blank_stars
    5 - rating.to_i
  end
 
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :storextra
  belongs_to :user
  
end

app/models/order.rb
class Order < ApplicationRecord
  before_create -> { generate_number(hash_size) }
  belongs_to :product
  belongs_to :user
  #belongs_to :store
  belongs_to :billing, optional: true

  validates :number, uniqueness: true

  validates :number, uniqueness: true

  def generate_number(size)
    self.number ||= loop do
      random = random_candidate(size)
      break random unless self.class.exists?(number: random)
    end
  end

  def random_candidate(size)
    "#{hash_prefix}#{Array.new(size){rand(size)}.join}"
  end

  def hash_prefix
    "BO"
  end

  def hash_size
    9
  end

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :storextra
    belongs_to :store
    has_many :orders, dependent: :destroy
    has_many :users, through: :orders, dependent: :destroy
    has_one_attached :image ,dependent: :destroy

    validates :image, attached: true, content_type: [:png, :jpg, :jpeg]

   
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :storextras, dependent: :destroy

  #has_many :orders, dependent: :destroy
end

app/models/storextra.rb
class Storextra < ApplicationRecord
  belongs_to :store
  belongs_to :category
  has_one_attached :avatar, dependent: :destroy 
  has_many :comments, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :avatar, content_type: [:png, :jpg, :jpeg]
  default_scope {order("rating DESC")}
  def rating_prom (storextra)
    @storextra = storextra
    comments = Comment.all
    rating_prom = 0
    contador = 0
    @storextra.comments.each do |comment|
      rating_prom += comment.rating.to_i
      contador += 1
    end 
    if rating_prom != 0
      @storextra.rating = rating_prom / contador
      @storextra.save!
    end 
  end
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  has_one_attached :avatar, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :orders, dependent: :destroy 
  has_many :products, through: :orders, dependent: :destroy
  has_many :billings, dependent: :destroy 

  has_many :visits, class_name: "Ahoy::Visit"
  has_many :events, class_name: "Ahoy::Event"
  
  validates :avatar, content_type: [:png, :jpg, :jpeg]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name 
    end
  end

  def password_required?
    super && provider.blank?
  end
  def update_with_password(params, *options)
    if encrypted_password.blank? && provider.present?
      update_attributes(params, *options)  
    else
       super
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def avatar_for(user, width = '200', height = '200')
        @avatar = user.avatar
        if !@avatar.attached?
            @avatar_user = image_tag("shiba.jpg", alt: user.name, width: width, height: height)
        else
            @avatar_user = image_tag(@avatar, alt: user.name, width: width, height: height)
        end
        return @avatar_user
    end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storextras_helper.rb
module StorextrasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuscaTiendas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <a class="navbar-brand" href="<%=root_path%>">BuscaTiendas</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        </ul>
        <span class="navbar-text">
          <% if user_signed_in? %>
            <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
            <%= link_to 'Editar perfil', edit_user_registration_path %>
            <%= link_to 'Carrito de compras', orders_path%>
          <% elsif !store_signed_in? %>
           <%= link_to 'Crear cuenta para usuarios', new_user_registration_path %> | 
           <%= link_to 'Crear cuenta para tiendas', new_store_registration_path %> |
          <%= link_to 'Iniciar sesión Usuarios', new_user_session_path%> |
          <%= link_to 'Iniciar sesión para tiendas', new_store_session_path%>
          <% elsif store_signed_in? %>
           <%= link_to 'Editar perfil', edit_store_registration_path %>
            <%= link_to 'Cerrar sesión', destroy_store_session_path, method: :delete %>
          <% end %>
        </span>
      </div>
    </nav>
    <% if user_signed_in? %>
      <section class="user">
        <h3 class= "text-bold">Te damos la bienvenida: ¡<%= current_user.name%>!</h3><br>
        <%= avatar_for(current_user) %>
        <%#=image_tag current_user.avatar, style: 'height:150px; width:150px;' if current_user.avatar.attached?%><br>
        <strong> <%= link_to 'Perfil', user_path(current_user) %></strong>
      </section>
        <hr>
    <% elsif store_signed_in? %>
      <br>
     <h3 class= "text-bold">Te damos la bienvenida: ¡<%= current_store.name%>!</h3><br>
        <strong> <%= link_to 'Mi tienda', storextra_path(current_store) %></strong> |  <strong> <%= link_to 'Mi Perfil', store_path(current_store) %></strong>
      </section>
        <hr>
    <%end%>
      <br>
      <%= yield %>
    </div>
      <footer >
        <div class="footer" >
          <h5 class="mt-2 pt-3"> Esto es un proyecto en mantenimiento, ningún producto ni tienda es real.<span class="ml-4"> Noviembre 2020.</span> <span class="ml-4"><em>-Nbakai-</em> </span> </h5>
        </div>
    </footer>
  </body>
</html>